Repository JamongSoda/IntoHistory, pull requests merged in 2022-08, with the labels that each got.

#9 [Resource] Add person_json
  IntoHistory/Data/person_json.json
Labels: resource

#10 [Resource] Add course_json
  IntoHistory/Data/course_json.json
Labels: resource

#11 [Resource] Add JSON Data File
  IntoHistory/Data/course_json.json
  IntoHistory/Data/person_json.json
Labels: resource

#13 [Resource] course_json 파일 수정
  IntoHistory/Data/course_json.json
Labels: resource

#14 [Resource] Modify course_json file
  IntoHistory/Data/course_json.json
Labels: resource

#18 [!HOTFIX] json 파일이 xcode에서 보이지 않는 버그 수정
  IntoHistory.xcodeproj/project.pbxproj
Labels: !HOTFIX

#21 !HOTFIX:ambulance:: FIX JSONData file
  IntoHistory/Data/course_json.json
Labels: !HOTFIX

#19 [!HOTFIX] json 파일이 xcode에서 보이지 않는 버그 수정 (develop merge)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/Data/course_json.json
Labels: !HOTFIX

#22 [Feat] Add Filemanager(CourseJSON, PersonJSON)
  IntoHistory/Data/CourseData.swift
  IntoHistory/Data/LoadingCourseJSON.swift
  IntoHistory/Data/LoadingPersonJSON.swift
  IntoHistory/Data/PersonData.swift
Labels: feature

#23 [Feature] Add Filemanager(CourseJSON, PersonJSON)
  IntoHistory/Data/CourseData.swift
  IntoHistory/Data/LoadingCourseJSON.swift
  IntoHistory/Data/LoadingPersonJSON.swift
  IntoHistory/Data/PersonData.swift
Labels: feature

#27 [!HOTFIX] 일부 Xcode에서 시뮬레이터 보이지 않는 문제 수정
  IntoHistory.xcodeproj/project.pbxproj
Labels: !HOTFIX

#28 [!HOTFIX] 일부 Xcode에서 시뮬레이터 보이지 않는 문제 수정 (projectsetting to develop)
  IntoHistory.xcodeproj/project.pbxproj
Labels: !HOTFIX

#30 [Feature] Add Extension (Auto Layout & Color Extension)
  IntoHistory/Extension/AutoLayout+Extension.swift
  IntoHistory/Extension/Color+Extension.swift
Labels: feature

#36 [!HOTFIX] develop에서 Extension 파일이 보이지 않는 현상 해결
  IntoHistory.xcodeproj/project.pbxproj
Labels: !HOTFIX

#44 [Feat] 네이버 지도 출력
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/Assets.xcassets/AppIcon.appiconset/Contents.json
  IntoHistory/NMapViewController.swift
Labels: feature

#47 [Resource] 지도에 사용할 마커(핀) 이미지 추가
  IntoHistory/Assets.xcassets/NormalPins/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo1.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo1.imageset/NormalNo1.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo10.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo10.imageset/NormalNo10.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo11.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo11.imageset/NormalNo11.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo12.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo12.imageset/NormalNo12.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo2.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo2.imageset/NormalNo2.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo3.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo3.imageset/NormalNo3.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo4.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo4.imageset/NormalNo4.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo5.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo5.imageset/NormalNo5.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo6.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo6.imageset/NormalNo6.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo7.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo7.imageset/NormalNo7.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo8.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo8.imageset/NormalNo8.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo9.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo9.imageset/NormalNo9.png
  IntoHistory/Assets.xcassets/SelectedPins/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo1.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo1.imageset/SelectedNo1.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo10.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo10.imageset/SelectedNo10.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo11.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo11.imageset/SelectedNo11.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo12.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo12.imageset/SelectedNo12.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo2.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo2.imageset/SelectedNo2.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo3.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo3.imageset/SelectedNo3.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo4.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo4.imageset/SelectedNo4.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo5.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo5.imageset/SelectedNo5.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo6.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo6.imageset/SelectedNo6.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo7.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo7.imageset/SelectedNo7.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo8.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo8.imageset/SelectedNo8.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo9.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo9.imageset/SelectedNo9.png
  IntoHistory/CourseListViewController.swift
Labels: resource

#48 [!Feature] 네이버 지도 추가, 지도 마커(핀) 에셋 추가
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/Assets.xcassets/AppIcon.appiconset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo1.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo1.imageset/NormalNo1.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo10.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo10.imageset/NormalNo10.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo11.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo11.imageset/NormalNo11.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo12.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo12.imageset/NormalNo12.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo2.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo2.imageset/NormalNo2.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo3.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo3.imageset/NormalNo3.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo4.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo4.imageset/NormalNo4.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo5.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo5.imageset/NormalNo5.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo6.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo6.imageset/NormalNo6.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo7.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo7.imageset/NormalNo7.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo8.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo8.imageset/NormalNo8.png
  IntoHistory/Assets.xcassets/NormalPins/NormalNo9.imageset/Contents.json
  IntoHistory/Assets.xcassets/NormalPins/NormalNo9.imageset/NormalNo9.png
  IntoHistory/Assets.xcassets/SelectedPins/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo1.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo1.imageset/SelectedNo1.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo10.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo10.imageset/SelectedNo10.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo11.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo11.imageset/SelectedNo11.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo12.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo12.imageset/SelectedNo12.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo2.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo2.imageset/SelectedNo2.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo3.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo3.imageset/SelectedNo3.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo4.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo4.imageset/SelectedNo4.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo5.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo5.imageset/SelectedNo5.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo6.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo6.imageset/SelectedNo6.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo7.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo7.imageset/SelectedNo7.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo8.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo8.imageset/SelectedNo8.png
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo9.imageset/Contents.json
  IntoHistory/Assets.xcassets/SelectedPins/SelectedNo9.imageset/SelectedNo9.png
  IntoHistory/CourseListViewController.swift
  IntoHistory/NMapViewController.swift
Labels: feature

#50 [!HOTFIX] 데이터 폴더 타입 변경 (외부 폴더 -> 내부 폴더)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/NMapViewController.swift
Labels: !HOTFIX

#52 [Resource] Add ImageLiteral & selectedPinTypes
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/Data/CourseData.swift
  IntoHistory/Literal/ImageLiteral.swift
Labels: resource

#62 [Design] 내가 만나본 호국 영웅 뷰 레이아웃 생성
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/Assets.xcassets/LockedHero.imageset/Contents.json
  IntoHistory/Assets.xcassets/LockedHero.imageset/LockedHeroImage.png
  IntoHistory/Base.lproj/Main.storyboard
  IntoHistory/CollectionViewHeader.swift
  IntoHistory/HeroListCell.swift
  IntoHistory/HeroListDescriptionCell.swift
  IntoHistory/HeroListViewController.swift
  IntoHistory/Info.plist
  IntoHistory/SceneDelegate.swift
  IntoHistory/ViewController.swift
Labels: design

#66 [Resource] 사진이 없는 호국 영웅 이미지 추가
  IntoHistory/Assets.xcassets/NoImageHero.imageset/Contents.json
  IntoHistory/Assets.xcassets/NoImageHero.imageset/NoImageHero.png
Labels: resource

#55 [Feature] AR뷰 추가
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/Extension/Color+Extension.swift
  IntoHistory/Info.plist
  IntoHistory/Screens/ARView/ARViewController.swift
  IntoHistory/Screens/ARView/SupportViews/ARView.storyboard
  IntoHistory/Screens/ARView/SupportViews/TempButtonViewController.swift
Labels: feature

#63 [Design] 내가 만나본 호국 영웅 뷰 레이아웃 생성 (Merge herolistview to develop)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/Assets.xcassets/LockedHero.imageset/Contents.json
  IntoHistory/Assets.xcassets/LockedHero.imageset/LockedHeroImage.png
  IntoHistory/Assets.xcassets/NoImageHero.imageset/Contents.json
  IntoHistory/Assets.xcassets/NoImageHero.imageset/NoImageHero.png
  IntoHistory/Base.lproj/Main.storyboard
  IntoHistory/CollectionViewHeader.swift
  IntoHistory/HeroListCell.swift
  IntoHistory/HeroListDescriptionCell.swift
  IntoHistory/HeroListViewController.swift
  IntoHistory/Info.plist
  IntoHistory/SceneDelegate.swift
  IntoHistory/ViewController.swift
Labels: design

#76 [!HOTFIX] 집 나간 NMapViewController.swift 파일 복구
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/NMapViewController.swift
Labels: !HOTFIX

#77 [!HOTFIX] 집 나간 NMapViewController.swift 파일 복구 (Merge bugfix to develop)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/NMapViewController.swift
Labels: !HOTFIX

#67 [Feature] AR화면 전환 방식 변경
  IntoHistory/Screens/ARView/SupportViews/TempButtonViewController.swift
Labels: feature

#80 [!HOTFIX] 파일 매니저에서 json 파일을 정상적으로 불러오지 못하는 버그 수정
  IntoHistory.xcodeproj/project.pbxproj
Labels: !HOTFIX

#81 [!HOTFIX] 파일 매니저에서 json 파일을 정상적으로 불러오지 못하는 버그 수정 (Merge bugfix to develop)
  IntoHistory.xcodeproj/project.pbxproj
Labels: !HOTFIX

#85 [!Feature] 좌표에 따른 Pin위치 호출, UIView extension추가
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/Assets.xcassets/AppIcon.appiconset/Contents.json
  IntoHistory/Assets.xcassets/Marker/Contents.json
  IntoHistory/Assets.xcassets/Marker/NormalNo1.imageset/Contents.json
  IntoHistory/Assets.xcassets/Marker/NormalNo1.imageset/NormalNo1.png
  IntoHistory/Assets.xcassets/Marker/NormalNo10.imageset/Contents.json
  IntoHistory/Assets.xcassets/Marker/NormalNo10.imageset/NormalNo10.png
  IntoHistory/Assets.xcassets/Marker/NormalNo11.imageset/Contents.json
  IntoHistory/Assets.xcassets/Marker/NormalNo11.imageset/NormalNo11.png
  IntoHistory/Assets.xcassets/Marker/NormalNo12.imageset/Contents.json
  IntoHistory/Assets.xcassets/Marker/NormalNo12.imageset/NormalNo12.png
  IntoHistory/Assets.xcassets/Marker/NormalNo2.imageset/Contents.json
  IntoHistory/Assets.xcassets/Marker/NormalNo2.imageset/NormalNo2.png
  IntoHistory/Assets.xcassets/Marker/NormalNo3.imageset/Contents.json
  IntoHistory/Assets.xcassets/Marker/NormalNo3.imageset/NormalNo3.png
  IntoHistory/Assets.xcassets/Marker/NormalNo4.imageset/Contents.json
  IntoHistory/Assets.xcassets/Marker/NormalNo4.imageset/NormalNo4.png
  IntoHistory/Assets.xcassets/Marker/NormalNo5.imageset/Contents.json
  IntoHistory/Assets.xcassets/Marker/NormalNo5.imageset/NormalNo5.png
  IntoHistory/Assets.xcassets/Marker/NormalNo6.imageset/Contents.json
  IntoHistory/Assets.xcassets/Marker/NormalNo6.imageset/NormalNo6.png
  IntoHistory/Assets.xcassets/Marker/NormalNo7.imageset/Contents.json
  IntoHistory/Assets.xcassets/Marker/NormalNo7.imageset/NormalNo7.png
  IntoHistory/Assets.xcassets/Marker/NormalNo8.imageset/Contents.json
  IntoHistory/Assets.xcassets/Marker/NormalNo8.imageset/NormalNo8.png
  IntoHistory/Assets.xcassets/Marker/NormalNo9.imageset/Contents.json
  IntoHistory/Assets.xcassets/Marker/NormalNo9.imageset/NormalNo9.png
  IntoHistory/Assets.xcassets/Pin/Contents.json
  IntoHistory/Assets.xcassets/Pin/SelectedNo1.imageset/Contents.json
  IntoHistory/Assets.xcassets/Pin/SelectedNo1.imageset/SelectedNo1.png
  IntoHistory/Assets.xcassets/Pin/SelectedNo10.imageset/Contents.json
  IntoHistory/Assets.xcassets/Pin/SelectedNo10.imageset/SelectedNo10.png
  IntoHistory/Assets.xcassets/Pin/SelectedNo11.imageset/Contents.json
  IntoHistory/Assets.xcassets/Pin/SelectedNo11.imageset/SelectedNo11.png
  IntoHistory/Assets.xcassets/Pin/SelectedNo12.imageset/Contents.json
  IntoHistory/Assets.xcassets/Pin/SelectedNo12.imageset/SelectedNo12.png
  IntoHistory/Assets.xcassets/Pin/SelectedNo2.imageset/Contents.json
  IntoHistory/Assets.xcassets/Pin/SelectedNo2.imageset/SelectedNo2.png
  IntoHistory/Assets.xcassets/Pin/SelectedNo3.imageset/Contents.json
  IntoHistory/Assets.xcassets/Pin/SelectedNo3.imageset/SelectedNo3.png
  IntoHistory/Assets.xcassets/Pin/SelectedNo4.imageset/Contents.json
  IntoHistory/Assets.xcassets/Pin/SelectedNo4.imageset/SelectedNo4.png
  IntoHistory/Assets.xcassets/Pin/SelectedNo5.imageset/Contents.json
  IntoHistory/Assets.xcassets/Pin/SelectedNo5.imageset/SelectedNo5.png
  IntoHistory/Assets.xcassets/Pin/SelectedNo6.imageset/Contents.json
  IntoHistory/Assets.xcassets/Pin/SelectedNo6.imageset/SelectedNo6.png
  IntoHistory/Assets.xcassets/Pin/SelectedNo7.imageset/Contents.json
  IntoHistory/Assets.xcassets/Pin/SelectedNo7.imageset/SelectedNo7.png
  IntoHistory/Assets.xcassets/Pin/SelectedNo8.imageset/Contents.json
  IntoHistory/Assets.xcassets/Pin/SelectedNo8.imageset/SelectedNo8.png
  IntoHistory/Assets.xcassets/Pin/SelectedNo9.imageset/Contents.json
  IntoHistory/Assets.xcassets/Pin/SelectedNo9.imageset/SelectedNo9.png
  IntoHistory/CourseListView/CourseListCell.swift
  IntoHistory/CourseListView/CourseListViewController.swift
  IntoHistory/CourseUIComponent/CourseListUIComponents.swift
  IntoHistory/Extension/UIView+Extension.swift
  IntoHistory/Literal/ImageLiteral.swift
  IntoHistory/NMapViewController.swift
Labels: feature, !fast

#84 [!Feature] 코어데이터 추가 (Merge coredata to develop)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/AppDelegate.swift
  IntoHistory/Coredata/CourseEntity+CoreDataClass.swift
  IntoHistory/Coredata/CourseEntity+CoreDataProperties.swift
  IntoHistory/Coredata/HeroEntity+CoreDataClass.swift
  IntoHistory/Coredata/HeroEntity+CoreDataProperties.swift
  IntoHistory/Coredata/Model.xcdatamodeld/.xccurrentversion
  IntoHistory/Coredata/Model.xcdatamodeld/IntoHistory.xcdatamodel/contents
  IntoHistory/Coredata/PinEntity+CoreDataClass.swift
  IntoHistory/Coredata/PinEntity+CoreDataProperties.swift
  IntoHistory/IntoHistory.xcdatamodeld/IntoHistory.xcdatamodel/contents
  IntoHistory/MainView/MainViewController.swift
Labels: feature, !fast

#87 [Feature] Add DetailCourseView(상세내용 뷰 레이아웃)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/DetailCourseView/DetailCourseCell.swift
  IntoHistory/DetailCourseView/DetailCourseHeader.swift
  IntoHistory/DetailCourseView/DetailCourseViewController.swift
Labels: feature, !fast

#73 [Design] 호국 영웅 상세정보 보기 팝업 레이아웃 추가 (Merge herolistview to develop)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/CollectionViewHeader.swift
  IntoHistory/Extension/Color+Extension.swift
  IntoHistory/Extension/UIViewContorller+Extension.swift
  IntoHistory/HeroDetailViewController.swift
  IntoHistory/HeroListCell.swift
  IntoHistory/HeroListDescriptionCell.swift
  IntoHistory/HeroListViewController.swift
Labels: design

#93 [Resource] 영웅별 사진 및 일러스트 추가
  IntoHistory/Assets.xcassets/AppIcon.appiconset/Contents.json
  IntoHistory/Assets.xcassets/Hero01.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero01.imageset/Hero01.png
  IntoHistory/Assets.xcassets/Hero02.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero02.imageset/Hero02.png
  IntoHistory/Assets.xcassets/Hero03.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero03.imageset/Hero03.png
  IntoHistory/Assets.xcassets/Hero04.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero04.imageset/Hero04.png
  IntoHistory/Assets.xcassets/Hero05.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero05.imageset/Hero05.png
  IntoHistory/Assets.xcassets/Hero06.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero06.imageset/Hero06.png
  IntoHistory/Assets.xcassets/Hero07.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero07.imageset/Hero07.png
  IntoHistory/Assets.xcassets/Hero08.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero08.imageset/Hero08.png
  IntoHistory/Assets.xcassets/Hero09.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero09.imageset/Hero09.png
  IntoHistory/Assets.xcassets/Hero10.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero10.imageset/Hero10.png
  IntoHistory/Assets.xcassets/Hero11.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero11.imageset/Hero11.png
  IntoHistory/Assets.xcassets/Hero12.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero12.imageset/Hero12.png
  IntoHistory/Assets.xcassets/Hero13.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero13.imageset/Hero13.png
  IntoHistory/Assets.xcassets/Hero14.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero14.imageset/Hero14.png
  IntoHistory/Assets.xcassets/Hero15.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero15.imageset/Hero15.png
  IntoHistory/Assets.xcassets/Hero16.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero16.imageset/Hero16.png
  IntoHistory/Assets.xcassets/Hero17.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero17.imageset/Hero17.png
  IntoHistory/Assets.xcassets/Hero18.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero18.imageset/Hero18.png
  IntoHistory/Assets.xcassets/Hero19.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero19.imageset/Hero19.png
  IntoHistory/Assets.xcassets/Hero20.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero20.imageset/Hero20.png
  IntoHistory/Assets.xcassets/Hero21.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero21.imageset/Hero21.png
  IntoHistory/Assets.xcassets/Hero22.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero22.imageset/Hero22.png
  IntoHistory/Assets.xcassets/Hero23.imageset/Contents.json
  IntoHistory/Assets.xcassets/Hero23.imageset/Hero23.png
Labels: resource

#96 [!Resource] json 파일 수정 (Merge json to develop 재PR)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/Data/CourseData.swift
  IntoHistory/Data/LoadingPersonJSON.swift
  IntoHistory/Data/PersonData.swift
  IntoHistory/Data/course_json.json
  IntoHistory/Data/person_json.json
Labels: resource, !fast

#102 [Feature] 호국 선열 목록 뷰 전체 호국 선열 목록 데이터 가져와서 출력
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/Assets.xcassets/NoImageHero.imageset/NoImageHero.png
  IntoHistory/Coredata/CourseEntity+CoreDataProperties.swift
  IntoHistory/Coredata/HeroEntity+CoreDataProperties.swift
  IntoHistory/Coredata/PinEntity+CoreDataProperties.swift
  IntoHistory/Data/CourseData.swift
  IntoHistory/HeroListCell.swift
  IntoHistory/HeroListViewController.swift
  IntoHistory/MainView/MainViewController.swift
  IntoHistory/NMapViewController.swift
Labels: feature

#103 [Feature] 영웅 목록에서 만나본 영웅과 만나보지 못한 영웅 이미지 다르게 보이게하는 기능 추가
  IntoHistory/HeroListViewController.swift
  IntoHistory/Literal/ImageLiteral.swift
  IntoHistory/MainView/MainViewController.swift
Labels: feature

#104 [!Feature] 호국 선열 목록 뷰 전체 목록 가져와서 보여주고 만나본지 여부에 따라 이미지 다르게 하는 기능 추가 (Merge herolist to develop)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/Assets.xcassets/NoImageHero.imageset/NoImageHero.png
  IntoHistory/Coredata/CourseEntity+CoreDataProperties.swift
  IntoHistory/Coredata/HeroEntity+CoreDataProperties.swift
  IntoHistory/Coredata/PinEntity+CoreDataProperties.swift
  IntoHistory/Data/CourseData.swift
  IntoHistory/HeroListCell.swift
  IntoHistory/HeroListViewController.swift
  IntoHistory/Literal/ImageLiteral.swift
  IntoHistory/MainView/MainViewController.swift
  IntoHistory/NMapViewController.swift
Labels: feature, !fast

#99 [Feature] 영웅을 클릭했을 때 모달 띄우고, 닫기 버튼 클릭으로 모달 닫는 기능 추가 (Merge heropopup to develop)
  IntoHistory/HeroDetailViewController.swift
  IntoHistory/HeroListViewController.swift
  IntoHistory/NMapViewController.swift
Labels: feature

#105 [Feature] Add FloatingView of nmap & Changing marker(pin)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/CourseListView/CourseListCell.swift
  IntoHistory/CourseListView/CourseListViewController.swift
  IntoHistory/DetailCourseView/DetailCourseCell.swift
  IntoHistory/DetailCourseView/DetailCourseViewController.swift
  IntoHistory/Info.plist
  IntoHistory/NMapViewController.swift
Labels: feature

#109 [Feature] 영웅 상세 보기 기능 추가 및 코어데이터 매니저 추가
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/Coredata/CoreDataManager.swift
  IntoHistory/Data/course_json.json
  IntoHistory/HeroDetailViewController.swift
  IntoHistory/HeroListViewController.swift
  IntoHistory/MainView/MainViewController.swift
Labels: feature

#111 [Feature] 위치기반 Notification 구현
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/AppDelegate.swift
  IntoHistory/Info.plist
  IntoHistory/LocationService.swift
  IntoHistory/MainView/MainViewController.swift
Labels: feature

#115 [Feature] mainView 칠판에 적절한 text띄우는 기능 추가
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/Extension/Date+Extension.swift
  IntoHistory/Info.plist
  IntoHistory/MainView/BlackBoardTextData.swift
  IntoHistory/MainView/MainViewController.swift
  IntoHistory/ulsanjunggu.ttf
Labels: feature

#113 [Feature] 영웅 상세 보기 기능 추가 및 코어데이터 매니저 추가 (Merge heropopup to develop)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/AppDelegate.swift
  IntoHistory/Coredata/CoreDataManager.swift
  IntoHistory/Coredata/CourseEntity+CoreDataClass.swift
  IntoHistory/Coredata/CourseEntity+CoreDataProperties.swift
  IntoHistory/Coredata/HeroEntity+CoreDataClass.swift
  IntoHistory/Coredata/HeroEntity+CoreDataProperties.swift
  IntoHistory/Coredata/PinEntity+CoreDataClass.swift
  IntoHistory/Coredata/PinEntity+CoreDataProperties.swift
  IntoHistory/Data/course_json.json
  IntoHistory/HeroDetailViewController.swift
  IntoHistory/HeroListViewController.swift
  IntoHistory/MainView/MainViewController.swift
Labels: feature

#106 [!Feature] Add FloatingView of nmap & Changing marker(pin)
  IntoHistory/CourseListView/CourseListCell.swift
  IntoHistory/CourseListView/CourseListViewController.swift
  IntoHistory/DetailCourseView/DetailCourseCell.swift
  IntoHistory/DetailCourseView/DetailCourseViewController.swift
  IntoHistory/Info.plist
  IntoHistory/NMapViewController.swift
Labels: feature, !fast

#116 [Feature] mainView 칠판에 적절한 text띄우는 기능 추가 (Merge mainViewBoard to develop)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/Extension/Date+Extension.swift
  IntoHistory/Info.plist
  IntoHistory/MainView/BlackBoardTextData.swift
  IntoHistory/MainView/MainViewController.swift
  IntoHistory/ulsanjunggu.ttf
Labels: feature

#117 [Feature] ARView UI 추가 (Merge arview to develop)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/Assets.xcassets/heroBallImage.imageset/Contents.json
  IntoHistory/Assets.xcassets/heroBallImage.imageset/heroBallImage.png
  IntoHistory/Extension/Color+Extension.swift
  IntoHistory/Info.plist
  IntoHistory/Screens/ARView/ARViewController.swift
  IntoHistory/Screens/ARView/SupportViews/ARView.storyboard
  IntoHistory/Screens/ARView/SupportViews/TempButtonViewController.swift
Labels: feature

#114 [Feature] 위치기반 notification 기능 구현 (Merge notification to develop)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/AppDelegate.swift
  IntoHistory/Info.plist
  IntoHistory/LocationService.swift
  IntoHistory/MainView/MainViewController.swift
Labels: feature

#127 [!Feature] 프로젝트 사망으로 arview 코드 복사해서 다시 작성 (Merge arview_new to develop)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/ARView/ARView.storyboard
  IntoHistory/ARView/ARViewController.swift
  IntoHistory/ARView/TempButtonViewController.swift
Labels: feature

#132 [Fix] DetailCourseView SafeArea 색상 추가(흰색)
  IntoHistory/ChangeViewController.swift
  IntoHistory/DetailCourseView/DetailCourseViewController.swift
Labels: fix

#133 [Fix] 다른 뷰에 갔다오면 이전 뷰의 네비게이션 타이틀이 남는 버그 수정 (Merge bugfix to develop)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/CourseListView/CourseListViewController.swift
  IntoHistory/DetailCourseView/DetailCourseViewController.swift
  IntoHistory/HeroListView/CollectionViewHeader.swift
  IntoHistory/HeroListView/HeroDetailViewController.swift
  IntoHistory/HeroListView/HeroListCell.swift
  IntoHistory/HeroListView/HeroListDescriptionCell.swift
  IntoHistory/HeroListView/HeroListViewController.swift
  IntoHistory/MainView/MainViewController.swift
Labels: fix

#130 [Feature] 지도, 상세코스 데이터 바인딩 및 JSON데이터 수정(Merge to Develop)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/Assets.xcassets/Marker/NormalNo13.imageset/Contents.json
  IntoHistory/Assets.xcassets/Marker/NormalNo13.imageset/NormalNo13.png
  IntoHistory/Assets.xcassets/Pin/SelectedNo13.imageset/Contents.json
  IntoHistory/Assets.xcassets/Pin/SelectedNo13.imageset/SelectedNo13.png
  IntoHistory/ChangeViewController.swift
  IntoHistory/Coredata/CoreDataManager.swift
  IntoHistory/CourseListView/CourseListCell.swift
  IntoHistory/CourseListView/CourseListViewController.swift
  IntoHistory/Data/CourseData.swift
  IntoHistory/Data/course_json.json
  IntoHistory/DetailCourseView/DetailCourseHeader.swift
  IntoHistory/DetailCourseView/DetailCourseViewController.swift
  IntoHistory/Literal/ImageLiteral.swift
  IntoHistory/NMapViewController.swift
Labels: feature

#138 [Feature] 장소 방문 시 지도 마커(핀) 색상 변경
  IntoHistory/Assets.xcassets/Marker/VisitedMarker.imageset/Contents.json
  IntoHistory/Assets.xcassets/Marker/VisitedMarker.imageset/VisitedMarker.png
  IntoHistory/CourseListView/CourseListCell.swift
  IntoHistory/CourseUIComponent/CourseListUIComponents.swift
  IntoHistory/Data/CourseData.swift
  IntoHistory/Data/course_json.json
  IntoHistory/DetailCourseView/DetailCourseHeader.swift
  IntoHistory/DetailCourseView/DetailCourseViewController.swift
  IntoHistory/Literal/ImageLiteral.swift
  IntoHistory/NMapViewController.swift
Labels: feature

#139 [Feature] notificatoin에 해당 지역명 추가 및 updatePinIsVisite
  IntoHistory/AppDelegate.swift
  IntoHistory/LocationService.swift
Labels: feature

#145 [!Feature] ARView 화면 연결 (맨 마지막 화면만 아직 미구현)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/ARView/ARViewController.swift
  IntoHistory/ARView/HeroCollectedViewController.swift
  IntoHistory/ARView/TempButtonViewController.swift
  IntoHistory/DetailCourseView/DetailCourseFooter.swift
  IntoHistory/DetailCourseView/DetailCourseViewController.swift
Labels: feature

#142 [!Hotfix] 맵 뷰 메모리 누수 버그 해결 및 카메라 이동시 맵 핀 해제 기능 추가
  IntoHistory/NMapViewController.swift
Labels: !HOTFIX

#147 [!Feature] ARView 화면 연결 (Merge connectarview to develop)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/ARView/ARViewController.swift
  IntoHistory/ARView/HeroCollectedViewController.swift
  IntoHistory/ARView/TempButtonViewController.swift
  IntoHistory/DetailCourseView/DetailCourseFooter.swift
  IntoHistory/DetailCourseView/DetailCourseViewController.swift
Labels: feature

#148 [!Hotfix] 맵 뷰 메모리 누수 버그 해결 및 카메라 이동시 맵 핀 해제 기능 추가 (Merge bugfix to develop)
  IntoHistory/NMapViewController.swift
Labels: !HOTFIX

#149 [!Design] Navigation 타이틀이 적절하게 적용되도록 수정 및 Backbutton 없애기
  IntoHistory/ARView/HeroCollectedViewController.swift
  IntoHistory/ChangeViewController.swift
  IntoHistory/CourseListView/CourseListViewController.swift
  IntoHistory/DetailCourseView/DetailCourseViewController.swift
  IntoHistory/HeroListView/HeroListViewController.swift
  IntoHistory/MainView/MainViewController.swift
  IntoHistory/NMapViewController.swift
Labels: design

#144 [!HOTFIX] 실시간으로 위치를 파악해 중복알림이 가는 버그 수정(임시방편)
  IntoHistory/AppDelegate.swift
  IntoHistory/LocationService.swift
Labels: !HOTFIX

#152 [!Design] Navigation 타이틀이 적절하게 적용되도록 수정 및 Backbutton 없애기 (Merge navi to develop)
  IntoHistory/ARView/HeroCollectedViewController.swift
  IntoHistory/ChangeViewController.swift
  IntoHistory/CourseListView/CourseListViewController.swift
  IntoHistory/DetailCourseView/DetailCourseViewController.swift
  IntoHistory/HeroListView/HeroListViewController.swift
  IntoHistory/MainView/MainViewController.swift
  IntoHistory/NMapViewController.swift
Labels: design

#153 [Fix] LocationService 코드 수정 (Merge navi to develop)
  IntoHistory/AppDelegate.swift
  IntoHistory/LocationService.swift
Labels: fix

#155 [Chore] 다크모드 해제, 세로로 고정, 카메라 접근허용 plist 수정 (Merge "this branch" to develop)
  IntoHistory/AppDelegate.swift
  IntoHistory/Info.plist
Labels: chore

#158 [Feature] 데이터 바인딩, 맵 메모리 누수 해결, 영웅 목록 수정, 코스 버튼 수정 및 자잘한 수정 (Merge databinding to develop)
  IntoHistory/ARView/ARViewController.swift
  IntoHistory/ARView/HeroCollectedViewController.swift
  IntoHistory/AppDelegate.swift
  IntoHistory/DetailCourseView/DetailCourseViewController.swift
  IntoHistory/Extension/Color+Extension.swift
  IntoHistory/HeroListView/HeroListViewController.swift
  IntoHistory/NMapViewController.swift
Labels: feature

#159 [Design] 앱 정보 뷰 UI 추가
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/DetailCourseView/DetailCourseViewController.swift
  IntoHistory/MainView/AppInfoViewController.swift
  IntoHistory/MainView/BlackBoardTextData.swift
  IntoHistory/MainView/MainViewController.swift
Labels: design

#160 [Design] 앱 정보 뷰 UI 추가 (Merge appinfoview to develop)
  IntoHistory.xcodeproj/project.pbxproj
  IntoHistory/DetailCourseView/DetailCourseViewController.swift
  IntoHistory/MainView/AppInfoViewController.swift
  IntoHistory/MainView/BlackBoardTextData.swift
  IntoHistory/MainView/MainViewController.swift
Labels: design

#169 [Chore] 상세 코스 최하단 버튼 멘트 수정
  IntoHistory/DetailCourseView/DetailCourseViewController.swift
Labels: chore
